# This is a basic workflow to help you get started with Actions

name: deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  S3_BUCKET_NAME: "elasticbeanstalk-us-west-2-559355273819"
  APP_NAME: "VkToDiscordTransfer"
  ENV_NAME: "VkToDiscordTransfer"
  PACKAGE_NAME: "app-${{ github.sha }}.zip"
  AWS_REGION: "us-west-2"
  

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: git clone
        uses: actions/checkout@v1
        
      - name: create zip package
        run: zip -r ${{ env.PACKAGE_NAME }} ./
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        
      - name: copy package to s3 bucket
        run: aws s3 cp ${{ env.PACKAGE_NAME }} s3://${{ env.S3_BUCKET_NAME }}/
        
  cd:
    runs-on: ubuntu-latest
    needs: [ci]

    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create new ElasticBeanstalk Applicaiton Version
        run: |
            aws elasticbeanstalk create-application-version \
            --application-name ${{ env.APP_NAME }} \
            --source-bundle S3Bucket="${{ env.S3_BUCKET_NAME }}",S3Key="${{ env.PACKAGE_NAME }}" \
            --version-label "Ver-${{ github.sha }}" \
            --description "CommitSHA-${{ github.sha }}"

      - name: Deploy our new Application Version
        run : aws elasticbeanstalk update-environment --environment-name ${{ env.ENV_NAME }}
